version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: phpjasperExampleDb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sub_reports
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  php:
    image: geekcom/phpjasper
    container_name: phpjasperExample
    volumes:
      - .:/var/www/app
    tty: true
    links:
      - mysql