version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: phpjasperExampleDb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=phpjasper
      - MYSQL_DATABASE=sub_reports
      - MYSQL_USER=phpjasper
      - MYSQL_PASSWORD=phpjasper
  php:
    image: geekcom/phpjasper:latest
    container_name: phpjasperExample
    volumes:
      - .:/var/www/app
    tty: true
    links:
      - mysql
